# coding: utf-8

"""
    Events API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EventDates(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'startdate': 'datetime',
        'enddate': 'datetime',
        'expires': 'datetime'
    }

    attribute_map = {
        'startdate': 'startdate',
        'enddate': 'enddate',
        'expires': 'expires'
    }

    def __init__(self, startdate=None, enddate=None, expires=None):  # noqa: E501
        """EventDates - a model defined in Swagger"""  # noqa: E501
        self._startdate = None
        self._enddate = None
        self._expires = None
        self.discriminator = None
        if startdate is not None:
            self.startdate = startdate
        if enddate is not None:
            self.enddate = enddate
        if expires is not None:
            self.expires = expires

    @property
    def startdate(self):
        """Gets the startdate of this EventDates.  # noqa: E501


        :return: The startdate of this EventDates.  # noqa: E501
        :rtype: datetime
        """
        return self._startdate

    @startdate.setter
    def startdate(self, startdate):
        """Sets the startdate of this EventDates.


        :param startdate: The startdate of this EventDates.  # noqa: E501
        :type: datetime
        """

        self._startdate = startdate

    @property
    def enddate(self):
        """Gets the enddate of this EventDates.  # noqa: E501


        :return: The enddate of this EventDates.  # noqa: E501
        :rtype: datetime
        """
        return self._enddate

    @enddate.setter
    def enddate(self, enddate):
        """Sets the enddate of this EventDates.


        :param enddate: The enddate of this EventDates.  # noqa: E501
        :type: datetime
        """

        self._enddate = enddate

    @property
    def expires(self):
        """Gets the expires of this EventDates.  # noqa: E501


        :return: The expires of this EventDates.  # noqa: E501
        :rtype: datetime
        """
        return self._expires

    @expires.setter
    def expires(self, expires):
        """Sets the expires of this EventDates.


        :param expires: The expires of this EventDates.  # noqa: E501
        :type: datetime
        """

        self._expires = expires

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventDates, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventDates):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
