# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EventPlannedcoverage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uri': 'str',
        'type': 'str',
        'event': 'str',
        'dates': 'EventDates',
        'renditions': 'list[EventRenditions]'
    }

    attribute_map = {
        'uri': 'uri',
        'type': 'type',
        'event': 'event',
        'dates': 'dates',
        'renditions': 'renditions'
    }

    def __init__(self, uri=None, type=None, event=None, dates=None, renditions=None):  # noqa: E501
        """EventPlannedcoverage - a model defined in Swagger"""  # noqa: E501
        self._uri = None
        self._type = None
        self._event = None
        self._dates = None
        self._renditions = None
        self.discriminator = None
        if uri is not None:
            self.uri = uri
        if type is not None:
            self.type = type
        if event is not None:
            self.event = event
        if dates is not None:
            self.dates = dates
        if renditions is not None:
            self.renditions = renditions

    @property
    def uri(self):
        """Gets the uri of this EventPlannedcoverage.  # noqa: E501


        :return: The uri of this EventPlannedcoverage.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this EventPlannedcoverage.


        :param uri: The uri of this EventPlannedcoverage.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def type(self):
        """Gets the type of this EventPlannedcoverage.  # noqa: E501


        :return: The type of this EventPlannedcoverage.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this EventPlannedcoverage.


        :param type: The type of this EventPlannedcoverage.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def event(self):
        """Gets the event of this EventPlannedcoverage.  # noqa: E501


        :return: The event of this EventPlannedcoverage.  # noqa: E501
        :rtype: str
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this EventPlannedcoverage.


        :param event: The event of this EventPlannedcoverage.  # noqa: E501
        :type: str
        """

        self._event = event

    @property
    def dates(self):
        """Gets the dates of this EventPlannedcoverage.  # noqa: E501


        :return: The dates of this EventPlannedcoverage.  # noqa: E501
        :rtype: EventDates
        """
        return self._dates

    @dates.setter
    def dates(self, dates):
        """Sets the dates of this EventPlannedcoverage.


        :param dates: The dates of this EventPlannedcoverage.  # noqa: E501
        :type: EventDates
        """

        self._dates = dates

    @property
    def renditions(self):
        """Gets the renditions of this EventPlannedcoverage.  # noqa: E501


        :return: The renditions of this EventPlannedcoverage.  # noqa: E501
        :rtype: list[EventRenditions]
        """
        return self._renditions

    @renditions.setter
    def renditions(self, renditions):
        """Sets the renditions of this EventPlannedcoverage.


        :param renditions: The renditions of this EventPlannedcoverage.  # noqa: E501
        :type: list[EventRenditions]
        """

        self._renditions = renditions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventPlannedcoverage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventPlannedcoverage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
