openapi: 3.0.0
info:
  title: Event API
  version: "1.1"
servers:
- url: /
paths:
  /events:
    post:
      summary: Publish an event
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
        required: true
      responses:
        "201":
          description: Event created
        "400":
          description: Invalid input
components:
  schemas:
    Event:
      type: object
      properties:
        uri:
          type: string
        type:
          type: string
        title:
          type: string
        by:
          type: string
        language:
          type: string
        descriptions:
          type: array
          items:
            $ref: '#/components/schemas/Event_descriptions'
        altids:
          $ref: '#/components/schemas/Event_altids'
        commissionedby:
          type: array
          items:
            $ref: '#/components/schemas/Event_commissionedby'
        eventdetails:
          $ref: '#/components/schemas/Event_eventdetails'
        headlines:
          type: array
          items:
            $ref: '#/components/schemas/Event_headlines'
        slugline:
          type: string
        places:
          type: array
          items:
            $ref: '#/components/schemas/Event_places'
        people:
          type: array
          items:
            $ref: '#/components/schemas/Event_people'
        subjects:
          type: array
          items:
            $ref: '#/components/schemas/Event_subjects'
        plannedcoverage:
          type: array
          items:
            $ref: '#/components/schemas/Event_plannedcoverage'
    Event_descriptions:
      type: object
      properties:
        role:
          type: string
        value:
          type: string
    Event_altids:
      type: object
      properties:
        title:
          type: array
          items:
            $ref: '#/components/schemas/Event_descriptions'
    Event_commissionedby:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
    Event_eventdetails_dates:
      type: object
      properties:
        startdate:
          type: string
          format: date-time
        enddate:
          type: string
          format: date-time
        duration:
          type: string
        firstcreated:
          type: string
          format: date-time
    Event_eventdetails_organiser:
      type: object
      properties:
        name:
          type: string
    Event_eventdetails_address:
      type: object
      properties:
        country:
          type: string
    Event_eventdetails_contactinfo:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/Event_eventdetails_address'
        value:
          type: string
    Event_eventdetails_infosource:
      type: object
      properties:
        name:
          type: string
        role:
          type: string
        uri:
          type: string
          format: uri
        literal:
          type: string
        contactinfo:
          type: array
          items:
            $ref: '#/components/schemas/Event_eventdetails_contactinfo'
    Event_eventdetails_ednote:
      type: object
      properties:
        contactinfo:
          type: string
    Event_eventdetails:
      type: object
      properties:
        dates:
          $ref: '#/components/schemas/Event_eventdetails_dates'
        embargoed:
          type: string
          format: date-time
        organiser:
          $ref: '#/components/schemas/Event_eventdetails_organiser'
        usageterms:
          type: string
        pubstatus:
          type: array
          items:
            type: string
        copyrightholder:
          type: string
        copyrightnotice:
          type: string
        location:
          type: string
        infosource:
          type: array
          items:
            $ref: '#/components/schemas/Event_eventdetails_infosource'
        ednote:
          $ref: '#/components/schemas/Event_eventdetails_ednote'
    Event_headlines:
      type: object
      properties:
        role:
          type: string
        contenttype:
          type: string
    Event_address:
      type: object
      properties:
        locality:
          type: string
        country:
          type: string
    Event_contactinfo:
      type: object
      properties:
        name:
          type: string
        address:
          $ref: '#/components/schemas/Event_address'
        value:
          type: string
    Event_places:
      type: object
      properties:
        name:
          type: string
        contactinfo:
          type: array
          items:
            $ref: '#/components/schemas/Event_contactinfo'
    Event_contactinfo_1:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/Event_address'
        value:
          type: string
    Event_people:
      type: object
      properties:
        name:
          type: string
        contactinfo:
          type: array
          items:
            $ref: '#/components/schemas/Event_contactinfo_1'
        relationship:
          type: string
    Event_subjects:
      type: object
      properties:
        name:
          type: string
        uri:
          type: string
        mediatopics:
          type: array
          items:
            type: string
    Event_dates:
      type: object
      properties:
        startdate:
          type: string
          format: date-time
        enddate:
          type: string
          format: date-time
        expires:
          type: string
          format: date-time
    Event_renditions:
      type: object
      properties:
        contenttype:
          type: string
        bitrate:
          type: string
        aspectratio:
          type: string
        videocodec:
          type: string
        format:
          type: string
    Event_plannedcoverage:
      type: object
      properties:
        uri:
          type: string
        type:
          type: string
        event:
          type: string
        dates:
          $ref: '#/components/schemas/Event_dates'
        renditions:
          type: array
          items:
            $ref: '#/components/schemas/Event_renditions'
