# coding: utf-8

"""
    Event API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.event_contactinfo import EventContactinfo  # noqa: E501
from swagger_client.rest import ApiException


class TestEventContactinfo(unittest.TestCase):
    """EventContactinfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventContactinfo(self):
        """Test EventContactinfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.event_contactinfo.EventContactinfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
