# coding: utf-8

"""
    News Events API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.news_event_genres import NewsEventGenres  # noqa: E501
from swagger_client.rest import ApiException


class TestNewsEventGenres(unittest.TestCase):
    """NewsEventGenres unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewsEventGenres(self):
        """Test NewsEventGenres"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.news_event_genres.NewsEventGenres()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
