# coding: utf-8

"""
    Event API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.event_address1 import EventAddress1  # noqa: E501
from swagger_client.rest import ApiException


class TestEventAddress1(unittest.TestCase):
    """EventAddress1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventAddress1(self):
        """Test EventAddress1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.event_address1.EventAddress1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
