# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.standard import Standard  # noqa: E501
from swagger_client.rest import ApiException


class TestStandard(unittest.TestCase):
    """Standard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStandard(self):
        """Test Standard"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.standard.Standard()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
