# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.event_rightsinfo import EventRightsinfo  # noqa: E501
from swagger_client.rest import ApiException


class TestEventRightsinfo(unittest.TestCase):
    """EventRightsinfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventRightsinfo(self):
        """Test EventRightsinfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.event_rightsinfo.EventRightsinfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
