# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inlineresponse201 import Inlineresponse201  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineresponse201(unittest.TestCase):
    """Inlineresponse201 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineresponse201(self):
        """Test Inlineresponse201"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inlineresponse201.Inlineresponse201()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
