# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.event_genres import EventGenres  # noqa: E501
from swagger_client.rest import ApiException


class TestEventGenres(unittest.TestCase):
    """EventGenres unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventGenres(self):
        """Test EventGenres"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.event_genres.EventGenres()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
