# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.datesobject_type_recurrence import DatesobjectTypeRecurrence  # noqa: E501
from swagger_client.rest import ApiException


class TestDatesobjectTypeRecurrence(unittest.TestCase):
    """DatesobjectTypeRecurrence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDatesobjectTypeRecurrence(self):
        """Test DatesobjectTypeRecurrence"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.datesobject_type_recurrence.DatesobjectTypeRecurrence()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
