# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CommissionedType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'by': 'str',
        '_true': 'datetime',
        'references': 'list[CommissionedTypeReferences]'
    }

    attribute_map = {
        'by': 'by',
        '_true': 'true',
        'references': 'references'
    }

    def __init__(self, by=None, _true=None, references=None):  # noqa: E501
        """CommissionedType - a model defined in Swagger"""  # noqa: E501
        self._by = None
        self.__true = None
        self._references = None
        self.discriminator = None
        if by is not None:
            self.by = by
        if _true is not None:
            self._true = _true
        if references is not None:
            self.references = references

    @property
    def by(self):
        """Gets the by of this CommissionedType.  # noqa: E501


        :return: The by of this CommissionedType.  # noqa: E501
        :rtype: str
        """
        return self._by

    @by.setter
    def by(self, by):
        """Sets the by of this CommissionedType.


        :param by: The by of this CommissionedType.  # noqa: E501
        :type: str
        """

        self._by = by

    @property
    def _true(self):
        """Gets the _true of this CommissionedType.  # noqa: E501


        :return: The _true of this CommissionedType.  # noqa: E501
        :rtype: datetime
        """
        return self.__true

    @_true.setter
    def _true(self, _true):
        """Sets the _true of this CommissionedType.


        :param _true: The _true of this CommissionedType.  # noqa: E501
        :type: datetime
        """

        self.__true = _true

    @property
    def references(self):
        """Gets the references of this CommissionedType.  # noqa: E501


        :return: The references of this CommissionedType.  # noqa: E501
        :rtype: list[CommissionedTypeReferences]
        """
        return self._references

    @references.setter
    def references(self, references):
        """Sets the references of this CommissionedType.


        :param references: The references of this CommissionedType.  # noqa: E501
        :type: list[CommissionedTypeReferences]
        """

        self._references = references

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CommissionedType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CommissionedType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
