# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ContactinfoType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'role': 'str',
        'lang': 'str',
        'name': 'str',
        'value': 'str',
        'address': 'object'
    }

    attribute_map = {
        'type': 'type',
        'role': 'role',
        'lang': 'lang',
        'name': 'name',
        'value': 'value',
        'address': 'address'
    }

    def __init__(self, type=None, role=None, lang=None, name=None, value=None, address=None):  # noqa: E501
        """ContactinfoType - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._role = None
        self._lang = None
        self._name = None
        self._value = None
        self._address = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if role is not None:
            self.role = role
        if lang is not None:
            self.lang = lang
        if name is not None:
            self.name = name
        if value is not None:
            self.value = value
        if address is not None:
            self.address = address

    @property
    def type(self):
        """Gets the type of this ContactinfoType.  # noqa: E501


        :return: The type of this ContactinfoType.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ContactinfoType.


        :param type: The type of this ContactinfoType.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def role(self):
        """Gets the role of this ContactinfoType.  # noqa: E501


        :return: The role of this ContactinfoType.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this ContactinfoType.


        :param role: The role of this ContactinfoType.  # noqa: E501
        :type: str
        """

        self._role = role

    @property
    def lang(self):
        """Gets the lang of this ContactinfoType.  # noqa: E501


        :return: The lang of this ContactinfoType.  # noqa: E501
        :rtype: str
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this ContactinfoType.


        :param lang: The lang of this ContactinfoType.  # noqa: E501
        :type: str
        """

        self._lang = lang

    @property
    def name(self):
        """Gets the name of this ContactinfoType.  # noqa: E501


        :return: The name of this ContactinfoType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ContactinfoType.


        :param name: The name of this ContactinfoType.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def value(self):
        """Gets the value of this ContactinfoType.  # noqa: E501


        :return: The value of this ContactinfoType.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ContactinfoType.


        :param value: The value of this ContactinfoType.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def address(self):
        """Gets the address of this ContactinfoType.  # noqa: E501

        The address of a person, place or organisation.  # noqa: E501

        :return: The address of this ContactinfoType.  # noqa: E501
        :rtype: object
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this ContactinfoType.

        The address of a person, place or organisation.  # noqa: E501

        :param address: The address of this ContactinfoType.  # noqa: E501
        :type: object
        """

        self._address = address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContactinfoType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContactinfoType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
