# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DatesobjectTypeRecurrenceRecurrencerules(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'frequency': 'str',
        'interval': 'str',
        'until': 'str',
        'count': 'str'
    }

    attribute_map = {
        'frequency': 'frequency',
        'interval': 'interval',
        'until': 'until',
        'count': 'count'
    }

    def __init__(self, frequency=None, interval=None, until=None, count=None):  # noqa: E501
        """DatesobjectTypeRecurrenceRecurrencerules - a model defined in Swagger"""  # noqa: E501
        self._frequency = None
        self._interval = None
        self._until = None
        self._count = None
        self.discriminator = None
        if frequency is not None:
            self.frequency = frequency
        if interval is not None:
            self.interval = interval
        if until is not None:
            self.until = until
        if count is not None:
            self.count = count

    @property
    def frequency(self):
        """Gets the frequency of this DatesobjectTypeRecurrenceRecurrencerules.  # noqa: E501


        :return: The frequency of this DatesobjectTypeRecurrenceRecurrencerules.  # noqa: E501
        :rtype: str
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """Sets the frequency of this DatesobjectTypeRecurrenceRecurrencerules.


        :param frequency: The frequency of this DatesobjectTypeRecurrenceRecurrencerules.  # noqa: E501
        :type: str
        """
        allowed_values = ["secondly", "minutely", "hourly", "daily", "weekly", "monthly", "yearly"]  # noqa: E501
        if frequency not in allowed_values:
            raise ValueError(
                "Invalid value for `frequency` ({0}), must be one of {1}"  # noqa: E501
                .format(frequency, allowed_values)
            )

        self._frequency = frequency

    @property
    def interval(self):
        """Gets the interval of this DatesobjectTypeRecurrenceRecurrencerules.  # noqa: E501


        :return: The interval of this DatesobjectTypeRecurrenceRecurrencerules.  # noqa: E501
        :rtype: str
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """Sets the interval of this DatesobjectTypeRecurrenceRecurrencerules.


        :param interval: The interval of this DatesobjectTypeRecurrenceRecurrencerules.  # noqa: E501
        :type: str
        """

        self._interval = interval

    @property
    def until(self):
        """Gets the until of this DatesobjectTypeRecurrenceRecurrencerules.  # noqa: E501


        :return: The until of this DatesobjectTypeRecurrenceRecurrencerules.  # noqa: E501
        :rtype: str
        """
        return self._until

    @until.setter
    def until(self, until):
        """Sets the until of this DatesobjectTypeRecurrenceRecurrencerules.


        :param until: The until of this DatesobjectTypeRecurrenceRecurrencerules.  # noqa: E501
        :type: str
        """

        self._until = until

    @property
    def count(self):
        """Gets the count of this DatesobjectTypeRecurrenceRecurrencerules.  # noqa: E501


        :return: The count of this DatesobjectTypeRecurrenceRecurrencerules.  # noqa: E501
        :rtype: str
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this DatesobjectTypeRecurrenceRecurrencerules.


        :param count: The count of this DatesobjectTypeRecurrenceRecurrencerules.  # noqa: E501
        :type: str
        """

        self._count = count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatesobjectTypeRecurrenceRecurrencerules, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatesobjectTypeRecurrenceRecurrencerules):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
