# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DatesobjectTypeRecurrence(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'recurrence_dates': 'list[TruncatedDateTimeType]',
        'recurrence_rules': 'list[DatesobjectTypeRecurrenceRecurrencerules]'
    }

    attribute_map = {
        'recurrence_dates': 'recurrence-dates',
        'recurrence_rules': 'recurrence-rules'
    }

    def __init__(self, recurrence_dates=None, recurrence_rules=None):  # noqa: E501
        """DatesobjectTypeRecurrence - a model defined in Swagger"""  # noqa: E501
        self._recurrence_dates = None
        self._recurrence_rules = None
        self.discriminator = None
        if recurrence_dates is not None:
            self.recurrence_dates = recurrence_dates
        if recurrence_rules is not None:
            self.recurrence_rules = recurrence_rules

    @property
    def recurrence_dates(self):
        """Gets the recurrence_dates of this DatesobjectTypeRecurrence.  # noqa: E501


        :return: The recurrence_dates of this DatesobjectTypeRecurrence.  # noqa: E501
        :rtype: list[TruncatedDateTimeType]
        """
        return self._recurrence_dates

    @recurrence_dates.setter
    def recurrence_dates(self, recurrence_dates):
        """Sets the recurrence_dates of this DatesobjectTypeRecurrence.


        :param recurrence_dates: The recurrence_dates of this DatesobjectTypeRecurrence.  # noqa: E501
        :type: list[TruncatedDateTimeType]
        """

        self._recurrence_dates = recurrence_dates

    @property
    def recurrence_rules(self):
        """Gets the recurrence_rules of this DatesobjectTypeRecurrence.  # noqa: E501


        :return: The recurrence_rules of this DatesobjectTypeRecurrence.  # noqa: E501
        :rtype: list[DatesobjectTypeRecurrenceRecurrencerules]
        """
        return self._recurrence_rules

    @recurrence_rules.setter
    def recurrence_rules(self, recurrence_rules):
        """Sets the recurrence_rules of this DatesobjectTypeRecurrence.


        :param recurrence_rules: The recurrence_rules of this DatesobjectTypeRecurrence.  # noqa: E501
        :type: list[DatesobjectTypeRecurrenceRecurrencerules]
        """

        self._recurrence_rules = recurrence_rules

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatesobjectTypeRecurrence, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatesobjectTypeRecurrence):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
