# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DatesobjectType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'startdate': 'TruncatedDateTimeType',
        'enddate': 'TruncatedDateTimeType',
        'duration': 'str',
        'recurrence': 'DatesobjectTypeRecurrence'
    }

    attribute_map = {
        'startdate': 'startdate',
        'enddate': 'enddate',
        'duration': 'duration',
        'recurrence': 'recurrence'
    }

    def __init__(self, startdate=None, enddate=None, duration=None, recurrence=None):  # noqa: E501
        """DatesobjectType - a model defined in Swagger"""  # noqa: E501
        self._startdate = None
        self._enddate = None
        self._duration = None
        self._recurrence = None
        self.discriminator = None
        if startdate is not None:
            self.startdate = startdate
        if enddate is not None:
            self.enddate = enddate
        if duration is not None:
            self.duration = duration
        if recurrence is not None:
            self.recurrence = recurrence

    @property
    def startdate(self):
        """Gets the startdate of this DatesobjectType.  # noqa: E501


        :return: The startdate of this DatesobjectType.  # noqa: E501
        :rtype: TruncatedDateTimeType
        """
        return self._startdate

    @startdate.setter
    def startdate(self, startdate):
        """Sets the startdate of this DatesobjectType.


        :param startdate: The startdate of this DatesobjectType.  # noqa: E501
        :type: TruncatedDateTimeType
        """

        self._startdate = startdate

    @property
    def enddate(self):
        """Gets the enddate of this DatesobjectType.  # noqa: E501


        :return: The enddate of this DatesobjectType.  # noqa: E501
        :rtype: TruncatedDateTimeType
        """
        return self._enddate

    @enddate.setter
    def enddate(self, enddate):
        """Sets the enddate of this DatesobjectType.


        :param enddate: The enddate of this DatesobjectType.  # noqa: E501
        :type: TruncatedDateTimeType
        """

        self._enddate = enddate

    @property
    def duration(self):
        """Gets the duration of this DatesobjectType.  # noqa: E501


        :return: The duration of this DatesobjectType.  # noqa: E501
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this DatesobjectType.


        :param duration: The duration of this DatesobjectType.  # noqa: E501
        :type: str
        """

        self._duration = duration

    @property
    def recurrence(self):
        """Gets the recurrence of this DatesobjectType.  # noqa: E501


        :return: The recurrence of this DatesobjectType.  # noqa: E501
        :rtype: DatesobjectTypeRecurrence
        """
        return self._recurrence

    @recurrence.setter
    def recurrence(self, recurrence):
        """Sets the recurrence of this DatesobjectType.


        :param recurrence: The recurrence of this DatesobjectType.  # noqa: E501
        :type: DatesobjectTypeRecurrence
        """

        self._recurrence = recurrence

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatesobjectType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatesobjectType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
