# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EventSubjects(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'rel': 'str',
        'uri': 'str',
        'literal': 'str',
        'creator': 'str',
        'relevance': 'int',
        'confidence': 'int'
    }

    attribute_map = {
        'name': 'name',
        'rel': 'rel',
        'uri': 'uri',
        'literal': 'literal',
        'creator': 'creator',
        'relevance': 'relevance',
        'confidence': 'confidence'
    }

    def __init__(self, name=None, rel=None, uri=None, literal=None, creator=None, relevance=None, confidence=None):  # noqa: E501
        """EventSubjects - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._rel = None
        self._uri = None
        self._literal = None
        self._creator = None
        self._relevance = None
        self._confidence = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if rel is not None:
            self.rel = rel
        if uri is not None:
            self.uri = uri
        if literal is not None:
            self.literal = literal
        if creator is not None:
            self.creator = creator
        if relevance is not None:
            self.relevance = relevance
        if confidence is not None:
            self.confidence = confidence

    @property
    def name(self):
        """Gets the name of this EventSubjects.  # noqa: E501


        :return: The name of this EventSubjects.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EventSubjects.


        :param name: The name of this EventSubjects.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def rel(self):
        """Gets the rel of this EventSubjects.  # noqa: E501


        :return: The rel of this EventSubjects.  # noqa: E501
        :rtype: str
        """
        return self._rel

    @rel.setter
    def rel(self, rel):
        """Sets the rel of this EventSubjects.


        :param rel: The rel of this EventSubjects.  # noqa: E501
        :type: str
        """

        self._rel = rel

    @property
    def uri(self):
        """Gets the uri of this EventSubjects.  # noqa: E501


        :return: The uri of this EventSubjects.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this EventSubjects.


        :param uri: The uri of this EventSubjects.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def literal(self):
        """Gets the literal of this EventSubjects.  # noqa: E501


        :return: The literal of this EventSubjects.  # noqa: E501
        :rtype: str
        """
        return self._literal

    @literal.setter
    def literal(self, literal):
        """Sets the literal of this EventSubjects.


        :param literal: The literal of this EventSubjects.  # noqa: E501
        :type: str
        """

        self._literal = literal

    @property
    def creator(self):
        """Gets the creator of this EventSubjects.  # noqa: E501


        :return: The creator of this EventSubjects.  # noqa: E501
        :rtype: str
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this EventSubjects.


        :param creator: The creator of this EventSubjects.  # noqa: E501
        :type: str
        """

        self._creator = creator

    @property
    def relevance(self):
        """Gets the relevance of this EventSubjects.  # noqa: E501


        :return: The relevance of this EventSubjects.  # noqa: E501
        :rtype: int
        """
        return self._relevance

    @relevance.setter
    def relevance(self, relevance):
        """Sets the relevance of this EventSubjects.


        :param relevance: The relevance of this EventSubjects.  # noqa: E501
        :type: int
        """

        self._relevance = relevance

    @property
    def confidence(self):
        """Gets the confidence of this EventSubjects.  # noqa: E501


        :return: The confidence of this EventSubjects.  # noqa: E501
        :rtype: int
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence):
        """Sets the confidence of this EventSubjects.


        :param confidence: The confidence of this EventSubjects.  # noqa: E501
        :type: int
        """

        self._confidence = confidence

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventSubjects, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventSubjects):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
