# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EventItemcount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rangefrom': 'int',
        'rangeto': 'int'
    }

    attribute_map = {
        'rangefrom': 'rangefrom',
        'rangeto': 'rangeto'
    }

    def __init__(self, rangefrom=None, rangeto=None):  # noqa: E501
        """EventItemcount - a model defined in Swagger"""  # noqa: E501
        self._rangefrom = None
        self._rangeto = None
        self.discriminator = None
        if rangefrom is not None:
            self.rangefrom = rangefrom
        if rangeto is not None:
            self.rangeto = rangeto

    @property
    def rangefrom(self):
        """Gets the rangefrom of this EventItemcount.  # noqa: E501


        :return: The rangefrom of this EventItemcount.  # noqa: E501
        :rtype: int
        """
        return self._rangefrom

    @rangefrom.setter
    def rangefrom(self, rangefrom):
        """Sets the rangefrom of this EventItemcount.


        :param rangefrom: The rangefrom of this EventItemcount.  # noqa: E501
        :type: int
        """

        self._rangefrom = rangefrom

    @property
    def rangeto(self):
        """Gets the rangeto of this EventItemcount.  # noqa: E501


        :return: The rangeto of this EventItemcount.  # noqa: E501
        :rtype: int
        """
        return self._rangeto

    @rangeto.setter
    def rangeto(self, rangeto):
        """Sets the rangeto of this EventItemcount.


        :param rangeto: The rangeto of this EventItemcount.  # noqa: E501
        :type: int
        """

        self._rangeto = rangeto

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventItemcount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventItemcount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
