# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EventAudiences(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'audience': 'str',
        'significance': 'int'
    }

    attribute_map = {
        'audience': 'audience',
        'significance': 'significance'
    }

    def __init__(self, audience=None, significance=None):  # noqa: E501
        """EventAudiences - a model defined in Swagger"""  # noqa: E501
        self._audience = None
        self._significance = None
        self.discriminator = None
        if audience is not None:
            self.audience = audience
        if significance is not None:
            self.significance = significance

    @property
    def audience(self):
        """Gets the audience of this EventAudiences.  # noqa: E501


        :return: The audience of this EventAudiences.  # noqa: E501
        :rtype: str
        """
        return self._audience

    @audience.setter
    def audience(self, audience):
        """Sets the audience of this EventAudiences.


        :param audience: The audience of this EventAudiences.  # noqa: E501
        :type: str
        """

        self._audience = audience

    @property
    def significance(self):
        """Gets the significance of this EventAudiences.  # noqa: E501


        :return: The significance of this EventAudiences.  # noqa: E501
        :rtype: int
        """
        return self._significance

    @significance.setter
    def significance(self, significance):
        """Sets the significance of this EventAudiences.


        :param significance: The significance of this EventAudiences.  # noqa: E501
        :type: int
        """

        self._significance = significance

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventAudiences, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventAudiences):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
