# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RenditionType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'items': 'list[object]',
        'name': 'str',
        'uri': 'str',
        'version': 'int',
        'versionguid': 'str',
        'href': 'str',
        'code': 'str',
        'signal': 'str',
        'transportprotocol': 'str',
        'maxbitrate': 'float',
        'cidr': 'str',
        'port': 'float',
        'srtpassword': 'str',
        'listeneraddress': 'str',
        'streamid': 'str',
        'minlatency': 'float',
        'codec': 'str',
        'scantype': 'str',
        'bitrate': 'float',
        'gop': 'float',
        'ratecontrolmode': 'str',
        'contenttype': 'str',
        'title': 'str',
        'generated': 'datetime',
        'height': 'float',
        'width': 'float',
        'sizeinbytes': 'float',
        'duration': 'float',
        'averagebitrate': 'float',
        'format': 'str',
        'originalfilename': 'str',
        'fileextension': 'str',
        'digest': 'str',
        'samplerate': 'float',
        'audiochannels': 'float',
        'audiobitrate': 'float',
        'aspectratio': 'str',
        'colourspace': 'str',
        'backgroundcolour': 'str',
        'orientation': 'str',
        'videocodec': 'str',
        'videoscaling': 'str',
        'framerate': 'float',
        'resolution': 'str',
        'audiocodec': 'str',
        'scene': 'str',
        'printsize': 'float',
        'poi': 'RenditionTypepoi'
    }

    attribute_map = {
        'items': 'items',
        'name': 'name',
        'uri': 'uri',
        'version': 'version',
        'versionguid': 'versionguid',
        'href': 'href',
        'code': 'code',
        'signal': 'signal',
        'transportprotocol': 'transportprotocol',
        'maxbitrate': 'maxbitrate',
        'cidr': 'cidr',
        'port': 'port',
        'srtpassword': 'srtpassword',
        'listeneraddress': 'listeneraddress',
        'streamid': 'streamid',
        'minlatency': 'minlatency',
        'codec': 'codec',
        'scantype': 'scantype',
        'bitrate': 'bitrate',
        'gop': 'gop',
        'ratecontrolmode': 'ratecontrolmode',
        'contenttype': 'contenttype',
        'title': 'title',
        'generated': 'generated',
        'height': 'height',
        'width': 'width',
        'sizeinbytes': 'sizeinbytes',
        'duration': 'duration',
        'averagebitrate': 'averagebitrate',
        'format': 'format',
        'originalfilename': 'originalfilename',
        'fileextension': 'fileextension',
        'digest': 'digest',
        'samplerate': 'samplerate',
        'audiochannels': 'audiochannels',
        'audiobitrate': 'audiobitrate',
        'aspectratio': 'aspectratio',
        'colourspace': 'colourspace',
        'backgroundcolour': 'backgroundcolour',
        'orientation': 'orientation',
        'videocodec': 'videocodec',
        'videoscaling': 'videoscaling',
        'framerate': 'framerate',
        'resolution': 'resolution',
        'audiocodec': 'audiocodec',
        'scene': 'scene',
        'printsize': 'printsize',
        'poi': 'poi'
    }

    def __init__(self, items=None, name=None, uri=None, version=None, versionguid=None, href=None, code=None, signal=None, transportprotocol=None, maxbitrate=None, cidr=None, port=None, srtpassword=None, listeneraddress=None, streamid=None, minlatency=None, codec=None, scantype=None, bitrate=None, gop=None, ratecontrolmode=None, contenttype=None, title=None, generated=None, height=None, width=None, sizeinbytes=None, duration=None, averagebitrate=None, format=None, originalfilename=None, fileextension=None, digest=None, samplerate=None, audiochannels=None, audiobitrate=None, aspectratio=None, colourspace=None, backgroundcolour=None, orientation=None, videocodec=None, videoscaling=None, framerate=None, resolution=None, audiocodec=None, scene=None, printsize=None, poi=None):  # noqa: E501
        """RenditionType - a model defined in Swagger"""  # noqa: E501
        self._items = None
        self._name = None
        self._uri = None
        self._version = None
        self._versionguid = None
        self._href = None
        self._code = None
        self._signal = None
        self._transportprotocol = None
        self._maxbitrate = None
        self._cidr = None
        self._port = None
        self._srtpassword = None
        self._listeneraddress = None
        self._streamid = None
        self._minlatency = None
        self._codec = None
        self._scantype = None
        self._bitrate = None
        self._gop = None
        self._ratecontrolmode = None
        self._contenttype = None
        self._title = None
        self._generated = None
        self._height = None
        self._width = None
        self._sizeinbytes = None
        self._duration = None
        self._averagebitrate = None
        self._format = None
        self._originalfilename = None
        self._fileextension = None
        self._digest = None
        self._samplerate = None
        self._audiochannels = None
        self._audiobitrate = None
        self._aspectratio = None
        self._colourspace = None
        self._backgroundcolour = None
        self._orientation = None
        self._videocodec = None
        self._videoscaling = None
        self._framerate = None
        self._resolution = None
        self._audiocodec = None
        self._scene = None
        self._printsize = None
        self._poi = None
        self.discriminator = None
        if items is not None:
            self.items = items
        if name is not None:
            self.name = name
        if uri is not None:
            self.uri = uri
        if version is not None:
            self.version = version
        if versionguid is not None:
            self.versionguid = versionguid
        if href is not None:
            self.href = href
        if code is not None:
            self.code = code
        if signal is not None:
            self.signal = signal
        if transportprotocol is not None:
            self.transportprotocol = transportprotocol
        if maxbitrate is not None:
            self.maxbitrate = maxbitrate
        if cidr is not None:
            self.cidr = cidr
        if port is not None:
            self.port = port
        if srtpassword is not None:
            self.srtpassword = srtpassword
        if listeneraddress is not None:
            self.listeneraddress = listeneraddress
        if streamid is not None:
            self.streamid = streamid
        if minlatency is not None:
            self.minlatency = minlatency
        if codec is not None:
            self.codec = codec
        if scantype is not None:
            self.scantype = scantype
        if bitrate is not None:
            self.bitrate = bitrate
        if gop is not None:
            self.gop = gop
        if ratecontrolmode is not None:
            self.ratecontrolmode = ratecontrolmode
        if contenttype is not None:
            self.contenttype = contenttype
        if title is not None:
            self.title = title
        if generated is not None:
            self.generated = generated
        if height is not None:
            self.height = height
        if width is not None:
            self.width = width
        if sizeinbytes is not None:
            self.sizeinbytes = sizeinbytes
        if duration is not None:
            self.duration = duration
        if averagebitrate is not None:
            self.averagebitrate = averagebitrate
        if format is not None:
            self.format = format
        if originalfilename is not None:
            self.originalfilename = originalfilename
        if fileextension is not None:
            self.fileextension = fileextension
        if digest is not None:
            self.digest = digest
        if samplerate is not None:
            self.samplerate = samplerate
        if audiochannels is not None:
            self.audiochannels = audiochannels
        if audiobitrate is not None:
            self.audiobitrate = audiobitrate
        if aspectratio is not None:
            self.aspectratio = aspectratio
        if colourspace is not None:
            self.colourspace = colourspace
        if backgroundcolour is not None:
            self.backgroundcolour = backgroundcolour
        if orientation is not None:
            self.orientation = orientation
        if videocodec is not None:
            self.videocodec = videocodec
        if videoscaling is not None:
            self.videoscaling = videoscaling
        if framerate is not None:
            self.framerate = framerate
        if resolution is not None:
            self.resolution = resolution
        if audiocodec is not None:
            self.audiocodec = audiocodec
        if scene is not None:
            self.scene = scene
        if printsize is not None:
            self.printsize = printsize
        if poi is not None:
            self.poi = poi

    @property
    def items(self):
        """Gets the items of this RenditionType.  # noqa: E501


        :return: The items of this RenditionType.  # noqa: E501
        :rtype: list[object]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this RenditionType.


        :param items: The items of this RenditionType.  # noqa: E501
        :type: list[object]
        """

        self._items = items

    @property
    def name(self):
        """Gets the name of this RenditionType.  # noqa: E501


        :return: The name of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RenditionType.


        :param name: The name of this RenditionType.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def uri(self):
        """Gets the uri of this RenditionType.  # noqa: E501


        :return: The uri of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this RenditionType.


        :param uri: The uri of this RenditionType.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def version(self):
        """Gets the version of this RenditionType.  # noqa: E501


        :return: The version of this RenditionType.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this RenditionType.


        :param version: The version of this RenditionType.  # noqa: E501
        :type: int
        """

        self._version = version

    @property
    def versionguid(self):
        """Gets the versionguid of this RenditionType.  # noqa: E501


        :return: The versionguid of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._versionguid

    @versionguid.setter
    def versionguid(self, versionguid):
        """Sets the versionguid of this RenditionType.


        :param versionguid: The versionguid of this RenditionType.  # noqa: E501
        :type: str
        """

        self._versionguid = versionguid

    @property
    def href(self):
        """Gets the href of this RenditionType.  # noqa: E501


        :return: The href of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this RenditionType.


        :param href: The href of this RenditionType.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def code(self):
        """Gets the code of this RenditionType.  # noqa: E501


        :return: The code of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this RenditionType.


        :param code: The code of this RenditionType.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def signal(self):
        """Gets the signal of this RenditionType.  # noqa: E501


        :return: The signal of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._signal

    @signal.setter
    def signal(self, signal):
        """Sets the signal of this RenditionType.


        :param signal: The signal of this RenditionType.  # noqa: E501
        :type: str
        """

        self._signal = signal

    @property
    def transportprotocol(self):
        """Gets the transportprotocol of this RenditionType.  # noqa: E501


        :return: The transportprotocol of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._transportprotocol

    @transportprotocol.setter
    def transportprotocol(self, transportprotocol):
        """Sets the transportprotocol of this RenditionType.


        :param transportprotocol: The transportprotocol of this RenditionType.  # noqa: E501
        :type: str
        """
        allowed_values = ["srtlistener", "srtcaller"]  # noqa: E501
        if transportprotocol not in allowed_values:
            raise ValueError(
                "Invalid value for `transportprotocol` ({0}), must be one of {1}"  # noqa: E501
                .format(transportprotocol, allowed_values)
            )

        self._transportprotocol = transportprotocol

    @property
    def maxbitrate(self):
        """Gets the maxbitrate of this RenditionType.  # noqa: E501


        :return: The maxbitrate of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._maxbitrate

    @maxbitrate.setter
    def maxbitrate(self, maxbitrate):
        """Sets the maxbitrate of this RenditionType.


        :param maxbitrate: The maxbitrate of this RenditionType.  # noqa: E501
        :type: float
        """

        self._maxbitrate = maxbitrate

    @property
    def cidr(self):
        """Gets the cidr of this RenditionType.  # noqa: E501


        :return: The cidr of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._cidr

    @cidr.setter
    def cidr(self, cidr):
        """Sets the cidr of this RenditionType.


        :param cidr: The cidr of this RenditionType.  # noqa: E501
        :type: str
        """

        self._cidr = cidr

    @property
    def port(self):
        """Gets the port of this RenditionType.  # noqa: E501


        :return: The port of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this RenditionType.


        :param port: The port of this RenditionType.  # noqa: E501
        :type: float
        """

        self._port = port

    @property
    def srtpassword(self):
        """Gets the srtpassword of this RenditionType.  # noqa: E501


        :return: The srtpassword of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._srtpassword

    @srtpassword.setter
    def srtpassword(self, srtpassword):
        """Sets the srtpassword of this RenditionType.


        :param srtpassword: The srtpassword of this RenditionType.  # noqa: E501
        :type: str
        """

        self._srtpassword = srtpassword

    @property
    def listeneraddress(self):
        """Gets the listeneraddress of this RenditionType.  # noqa: E501


        :return: The listeneraddress of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._listeneraddress

    @listeneraddress.setter
    def listeneraddress(self, listeneraddress):
        """Sets the listeneraddress of this RenditionType.


        :param listeneraddress: The listeneraddress of this RenditionType.  # noqa: E501
        :type: str
        """

        self._listeneraddress = listeneraddress

    @property
    def streamid(self):
        """Gets the streamid of this RenditionType.  # noqa: E501


        :return: The streamid of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._streamid

    @streamid.setter
    def streamid(self, streamid):
        """Sets the streamid of this RenditionType.


        :param streamid: The streamid of this RenditionType.  # noqa: E501
        :type: str
        """

        self._streamid = streamid

    @property
    def minlatency(self):
        """Gets the minlatency of this RenditionType.  # noqa: E501


        :return: The minlatency of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._minlatency

    @minlatency.setter
    def minlatency(self, minlatency):
        """Sets the minlatency of this RenditionType.


        :param minlatency: The minlatency of this RenditionType.  # noqa: E501
        :type: float
        """

        self._minlatency = minlatency

    @property
    def codec(self):
        """Gets the codec of this RenditionType.  # noqa: E501


        :return: The codec of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._codec

    @codec.setter
    def codec(self, codec):
        """Sets the codec of this RenditionType.


        :param codec: The codec of this RenditionType.  # noqa: E501
        :type: str
        """

        self._codec = codec

    @property
    def scantype(self):
        """Gets the scantype of this RenditionType.  # noqa: E501


        :return: The scantype of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._scantype

    @scantype.setter
    def scantype(self, scantype):
        """Sets the scantype of this RenditionType.


        :param scantype: The scantype of this RenditionType.  # noqa: E501
        :type: str
        """
        allowed_values = ["progressive", "interlaced"]  # noqa: E501
        if scantype not in allowed_values:
            raise ValueError(
                "Invalid value for `scantype` ({0}), must be one of {1}"  # noqa: E501
                .format(scantype, allowed_values)
            )

        self._scantype = scantype

    @property
    def bitrate(self):
        """Gets the bitrate of this RenditionType.  # noqa: E501


        :return: The bitrate of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._bitrate

    @bitrate.setter
    def bitrate(self, bitrate):
        """Sets the bitrate of this RenditionType.


        :param bitrate: The bitrate of this RenditionType.  # noqa: E501
        :type: float
        """

        self._bitrate = bitrate

    @property
    def gop(self):
        """Gets the gop of this RenditionType.  # noqa: E501


        :return: The gop of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._gop

    @gop.setter
    def gop(self, gop):
        """Sets the gop of this RenditionType.


        :param gop: The gop of this RenditionType.  # noqa: E501
        :type: float
        """

        self._gop = gop

    @property
    def ratecontrolmode(self):
        """Gets the ratecontrolmode of this RenditionType.  # noqa: E501


        :return: The ratecontrolmode of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._ratecontrolmode

    @ratecontrolmode.setter
    def ratecontrolmode(self, ratecontrolmode):
        """Sets the ratecontrolmode of this RenditionType.


        :param ratecontrolmode: The ratecontrolmode of this RenditionType.  # noqa: E501
        :type: str
        """
        allowed_values = ["CBR", "VBR", "QVBR"]  # noqa: E501
        if ratecontrolmode not in allowed_values:
            raise ValueError(
                "Invalid value for `ratecontrolmode` ({0}), must be one of {1}"  # noqa: E501
                .format(ratecontrolmode, allowed_values)
            )

        self._ratecontrolmode = ratecontrolmode

    @property
    def contenttype(self):
        """Gets the contenttype of this RenditionType.  # noqa: E501


        :return: The contenttype of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._contenttype

    @contenttype.setter
    def contenttype(self, contenttype):
        """Sets the contenttype of this RenditionType.


        :param contenttype: The contenttype of this RenditionType.  # noqa: E501
        :type: str
        """

        self._contenttype = contenttype

    @property
    def title(self):
        """Gets the title of this RenditionType.  # noqa: E501


        :return: The title of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this RenditionType.


        :param title: The title of this RenditionType.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def generated(self):
        """Gets the generated of this RenditionType.  # noqa: E501


        :return: The generated of this RenditionType.  # noqa: E501
        :rtype: datetime
        """
        return self._generated

    @generated.setter
    def generated(self, generated):
        """Sets the generated of this RenditionType.


        :param generated: The generated of this RenditionType.  # noqa: E501
        :type: datetime
        """

        self._generated = generated

    @property
    def height(self):
        """Gets the height of this RenditionType.  # noqa: E501


        :return: The height of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this RenditionType.


        :param height: The height of this RenditionType.  # noqa: E501
        :type: float
        """

        self._height = height

    @property
    def width(self):
        """Gets the width of this RenditionType.  # noqa: E501


        :return: The width of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this RenditionType.


        :param width: The width of this RenditionType.  # noqa: E501
        :type: float
        """

        self._width = width

    @property
    def sizeinbytes(self):
        """Gets the sizeinbytes of this RenditionType.  # noqa: E501


        :return: The sizeinbytes of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._sizeinbytes

    @sizeinbytes.setter
    def sizeinbytes(self, sizeinbytes):
        """Sets the sizeinbytes of this RenditionType.


        :param sizeinbytes: The sizeinbytes of this RenditionType.  # noqa: E501
        :type: float
        """

        self._sizeinbytes = sizeinbytes

    @property
    def duration(self):
        """Gets the duration of this RenditionType.  # noqa: E501


        :return: The duration of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this RenditionType.


        :param duration: The duration of this RenditionType.  # noqa: E501
        :type: float
        """

        self._duration = duration

    @property
    def averagebitrate(self):
        """Gets the averagebitrate of this RenditionType.  # noqa: E501


        :return: The averagebitrate of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._averagebitrate

    @averagebitrate.setter
    def averagebitrate(self, averagebitrate):
        """Sets the averagebitrate of this RenditionType.


        :param averagebitrate: The averagebitrate of this RenditionType.  # noqa: E501
        :type: float
        """

        self._averagebitrate = averagebitrate

    @property
    def format(self):
        """Gets the format of this RenditionType.  # noqa: E501


        :return: The format of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this RenditionType.


        :param format: The format of this RenditionType.  # noqa: E501
        :type: str
        """

        self._format = format

    @property
    def originalfilename(self):
        """Gets the originalfilename of this RenditionType.  # noqa: E501


        :return: The originalfilename of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._originalfilename

    @originalfilename.setter
    def originalfilename(self, originalfilename):
        """Sets the originalfilename of this RenditionType.


        :param originalfilename: The originalfilename of this RenditionType.  # noqa: E501
        :type: str
        """

        self._originalfilename = originalfilename

    @property
    def fileextension(self):
        """Gets the fileextension of this RenditionType.  # noqa: E501


        :return: The fileextension of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._fileextension

    @fileextension.setter
    def fileextension(self, fileextension):
        """Sets the fileextension of this RenditionType.


        :param fileextension: The fileextension of this RenditionType.  # noqa: E501
        :type: str
        """

        self._fileextension = fileextension

    @property
    def digest(self):
        """Gets the digest of this RenditionType.  # noqa: E501


        :return: The digest of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._digest

    @digest.setter
    def digest(self, digest):
        """Sets the digest of this RenditionType.


        :param digest: The digest of this RenditionType.  # noqa: E501
        :type: str
        """

        self._digest = digest

    @property
    def samplerate(self):
        """Gets the samplerate of this RenditionType.  # noqa: E501


        :return: The samplerate of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._samplerate

    @samplerate.setter
    def samplerate(self, samplerate):
        """Sets the samplerate of this RenditionType.


        :param samplerate: The samplerate of this RenditionType.  # noqa: E501
        :type: float
        """

        self._samplerate = samplerate

    @property
    def audiochannels(self):
        """Gets the audiochannels of this RenditionType.  # noqa: E501


        :return: The audiochannels of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._audiochannels

    @audiochannels.setter
    def audiochannels(self, audiochannels):
        """Sets the audiochannels of this RenditionType.


        :param audiochannels: The audiochannels of this RenditionType.  # noqa: E501
        :type: float
        """

        self._audiochannels = audiochannels

    @property
    def audiobitrate(self):
        """Gets the audiobitrate of this RenditionType.  # noqa: E501


        :return: The audiobitrate of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._audiobitrate

    @audiobitrate.setter
    def audiobitrate(self, audiobitrate):
        """Sets the audiobitrate of this RenditionType.


        :param audiobitrate: The audiobitrate of this RenditionType.  # noqa: E501
        :type: float
        """

        self._audiobitrate = audiobitrate

    @property
    def aspectratio(self):
        """Gets the aspectratio of this RenditionType.  # noqa: E501


        :return: The aspectratio of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._aspectratio

    @aspectratio.setter
    def aspectratio(self, aspectratio):
        """Sets the aspectratio of this RenditionType.


        :param aspectratio: The aspectratio of this RenditionType.  # noqa: E501
        :type: str
        """

        self._aspectratio = aspectratio

    @property
    def colourspace(self):
        """Gets the colourspace of this RenditionType.  # noqa: E501


        :return: The colourspace of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._colourspace

    @colourspace.setter
    def colourspace(self, colourspace):
        """Sets the colourspace of this RenditionType.


        :param colourspace: The colourspace of this RenditionType.  # noqa: E501
        :type: str
        """

        self._colourspace = colourspace

    @property
    def backgroundcolour(self):
        """Gets the backgroundcolour of this RenditionType.  # noqa: E501


        :return: The backgroundcolour of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._backgroundcolour

    @backgroundcolour.setter
    def backgroundcolour(self, backgroundcolour):
        """Sets the backgroundcolour of this RenditionType.


        :param backgroundcolour: The backgroundcolour of this RenditionType.  # noqa: E501
        :type: str
        """

        self._backgroundcolour = backgroundcolour

    @property
    def orientation(self):
        """Gets the orientation of this RenditionType.  # noqa: E501


        :return: The orientation of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._orientation

    @orientation.setter
    def orientation(self, orientation):
        """Sets the orientation of this RenditionType.


        :param orientation: The orientation of this RenditionType.  # noqa: E501
        :type: str
        """

        self._orientation = orientation

    @property
    def videocodec(self):
        """Gets the videocodec of this RenditionType.  # noqa: E501


        :return: The videocodec of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._videocodec

    @videocodec.setter
    def videocodec(self, videocodec):
        """Sets the videocodec of this RenditionType.


        :param videocodec: The videocodec of this RenditionType.  # noqa: E501
        :type: str
        """

        self._videocodec = videocodec

    @property
    def videoscaling(self):
        """Gets the videoscaling of this RenditionType.  # noqa: E501


        :return: The videoscaling of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._videoscaling

    @videoscaling.setter
    def videoscaling(self, videoscaling):
        """Sets the videoscaling of this RenditionType.


        :param videoscaling: The videoscaling of this RenditionType.  # noqa: E501
        :type: str
        """

        self._videoscaling = videoscaling

    @property
    def framerate(self):
        """Gets the framerate of this RenditionType.  # noqa: E501


        :return: The framerate of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._framerate

    @framerate.setter
    def framerate(self, framerate):
        """Sets the framerate of this RenditionType.


        :param framerate: The framerate of this RenditionType.  # noqa: E501
        :type: float
        """

        self._framerate = framerate

    @property
    def resolution(self):
        """Gets the resolution of this RenditionType.  # noqa: E501


        :return: The resolution of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._resolution

    @resolution.setter
    def resolution(self, resolution):
        """Sets the resolution of this RenditionType.


        :param resolution: The resolution of this RenditionType.  # noqa: E501
        :type: str
        """

        self._resolution = resolution

    @property
    def audiocodec(self):
        """Gets the audiocodec of this RenditionType.  # noqa: E501


        :return: The audiocodec of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._audiocodec

    @audiocodec.setter
    def audiocodec(self, audiocodec):
        """Sets the audiocodec of this RenditionType.


        :param audiocodec: The audiocodec of this RenditionType.  # noqa: E501
        :type: str
        """

        self._audiocodec = audiocodec

    @property
    def scene(self):
        """Gets the scene of this RenditionType.  # noqa: E501


        :return: The scene of this RenditionType.  # noqa: E501
        :rtype: str
        """
        return self._scene

    @scene.setter
    def scene(self, scene):
        """Sets the scene of this RenditionType.


        :param scene: The scene of this RenditionType.  # noqa: E501
        :type: str
        """

        self._scene = scene

    @property
    def printsize(self):
        """Gets the printsize of this RenditionType.  # noqa: E501


        :return: The printsize of this RenditionType.  # noqa: E501
        :rtype: float
        """
        return self._printsize

    @printsize.setter
    def printsize(self, printsize):
        """Sets the printsize of this RenditionType.


        :param printsize: The printsize of this RenditionType.  # noqa: E501
        :type: float
        """

        self._printsize = printsize

    @property
    def poi(self):
        """Gets the poi of this RenditionType.  # noqa: E501


        :return: The poi of this RenditionType.  # noqa: E501
        :rtype: RenditionTypepoi
        """
        return self._poi

    @poi.setter
    def poi(self, poi):
        """Sets the poi of this RenditionType.


        :param poi: The poi of this RenditionType.  # noqa: E501
        :type: RenditionTypepoi
        """

        self._poi = poi

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RenditionType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RenditionType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
