# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_events_delete(self):
        """Test case for events_delete

        Delete Event  # noqa: E501
        """
        pass

    def test_events_get(self):
        """Test case for events_get

        Select Event  # noqa: E501
        """
        pass

    def test_events_list_get(self):
        """Test case for events_list_get

        List Events  # noqa: E501
        """
        pass

    def test_events_post(self):
        """Test case for events_post

        Create Event  # noqa: E501
        """
        pass

    def test_events_put(self):
        """Test case for events_put

        Update Event  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
