# coding: utf-8

"""
    LPX API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.event_contactinfo1 import EventContactinfo1  # noqa: E501
from swagger_client.rest import ApiException


class TestEventContactinfo1(unittest.TestCase):
    """EventContactinfo1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventContactinfo1(self):
        """Test EventContactinfo1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.event_contactinfo1.EventContactinfo1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
