# coding: utf-8

# flake8: noqa

"""
    Event API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.default_api import DefaultApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.event import Event
from swagger_client.models.event_address import EventAddress
from swagger_client.models.event_altids import EventAltids
from swagger_client.models.event_commissionedby import EventCommissionedby
from swagger_client.models.event_contactinfo import EventContactinfo
from swagger_client.models.event_contactinfo1 import EventContactinfo1
from swagger_client.models.event_dates import EventDates
from swagger_client.models.event_descriptions import EventDescriptions
from swagger_client.models.event_eventdetails import EventEventdetails
from swagger_client.models.event_eventdetails_address import EventEventdetailsAddress
from swagger_client.models.event_eventdetails_contactinfo import EventEventdetailsContactinfo
from swagger_client.models.event_eventdetails_dates import EventEventdetailsDates
from swagger_client.models.event_eventdetails_ednote import EventEventdetailsEdnote
from swagger_client.models.event_eventdetails_infosource import EventEventdetailsInfosource
from swagger_client.models.event_eventdetails_organiser import EventEventdetailsOrganiser
from swagger_client.models.event_headlines import EventHeadlines
from swagger_client.models.event_people import EventPeople
from swagger_client.models.event_places import EventPlaces
from swagger_client.models.event_plannedcoverage import EventPlannedcoverage
from swagger_client.models.event_renditions import EventRenditions
from swagger_client.models.event_subjects import EventSubjects
