# coding: utf-8

# flake8: noqa
"""
    News Events API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.news_event import NewsEvent
from swagger_client.models.news_event_bodies import NewsEventBodies
from swagger_client.models.news_event_genres import NewsEventGenres
from swagger_client.models.news_event_headlines import NewsEventHeadlines
from swagger_client.models.news_event_standard import NewsEventStandard
from swagger_client.models.news_event_subjects import NewsEventSubjects
