# coding: utf-8

"""
    Event API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EventEventdetailsDates(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'startdate': 'datetime',
        'enddate': 'datetime',
        'duration': 'str',
        'firstcreated': 'datetime'
    }

    attribute_map = {
        'startdate': 'startdate',
        'enddate': 'enddate',
        'duration': 'duration',
        'firstcreated': 'firstcreated'
    }

    def __init__(self, startdate=None, enddate=None, duration=None, firstcreated=None):  # noqa: E501
        """EventEventdetailsDates - a model defined in Swagger"""  # noqa: E501
        self._startdate = None
        self._enddate = None
        self._duration = None
        self._firstcreated = None
        self.discriminator = None
        if startdate is not None:
            self.startdate = startdate
        if enddate is not None:
            self.enddate = enddate
        if duration is not None:
            self.duration = duration
        if firstcreated is not None:
            self.firstcreated = firstcreated

    @property
    def startdate(self):
        """Gets the startdate of this EventEventdetailsDates.  # noqa: E501


        :return: The startdate of this EventEventdetailsDates.  # noqa: E501
        :rtype: datetime
        """
        return self._startdate

    @startdate.setter
    def startdate(self, startdate):
        """Sets the startdate of this EventEventdetailsDates.


        :param startdate: The startdate of this EventEventdetailsDates.  # noqa: E501
        :type: datetime
        """

        self._startdate = startdate

    @property
    def enddate(self):
        """Gets the enddate of this EventEventdetailsDates.  # noqa: E501


        :return: The enddate of this EventEventdetailsDates.  # noqa: E501
        :rtype: datetime
        """
        return self._enddate

    @enddate.setter
    def enddate(self, enddate):
        """Sets the enddate of this EventEventdetailsDates.


        :param enddate: The enddate of this EventEventdetailsDates.  # noqa: E501
        :type: datetime
        """

        self._enddate = enddate

    @property
    def duration(self):
        """Gets the duration of this EventEventdetailsDates.  # noqa: E501


        :return: The duration of this EventEventdetailsDates.  # noqa: E501
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this EventEventdetailsDates.


        :param duration: The duration of this EventEventdetailsDates.  # noqa: E501
        :type: str
        """

        self._duration = duration

    @property
    def firstcreated(self):
        """Gets the firstcreated of this EventEventdetailsDates.  # noqa: E501


        :return: The firstcreated of this EventEventdetailsDates.  # noqa: E501
        :rtype: datetime
        """
        return self._firstcreated

    @firstcreated.setter
    def firstcreated(self, firstcreated):
        """Sets the firstcreated of this EventEventdetailsDates.


        :param firstcreated: The firstcreated of this EventEventdetailsDates.  # noqa: E501
        :type: datetime
        """

        self._firstcreated = firstcreated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventEventdetailsDates, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventEventdetailsDates):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
