# coding: utf-8

"""
    Event API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EventEventdetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dates': 'EventEventdetailsDates',
        'organiser': 'EventEventdetailsOrganiser'
    }

    attribute_map = {
        'dates': 'dates',
        'organiser': 'organiser'
    }

    def __init__(self, dates=None, organiser=None):  # noqa: E501
        """EventEventdetails - a model defined in Swagger"""  # noqa: E501
        self._dates = None
        self._organiser = None
        self.discriminator = None
        if dates is not None:
            self.dates = dates
        if organiser is not None:
            self.organiser = organiser

    @property
    def dates(self):
        """Gets the dates of this EventEventdetails.  # noqa: E501


        :return: The dates of this EventEventdetails.  # noqa: E501
        :rtype: EventEventdetailsDates
        """
        return self._dates

    @dates.setter
    def dates(self, dates):
        """Sets the dates of this EventEventdetails.


        :param dates: The dates of this EventEventdetails.  # noqa: E501
        :type: EventEventdetailsDates
        """

        self._dates = dates

    @property
    def organiser(self):
        """Gets the organiser of this EventEventdetails.  # noqa: E501


        :return: The organiser of this EventEventdetails.  # noqa: E501
        :rtype: EventEventdetailsOrganiser
        """
        return self._organiser

    @organiser.setter
    def organiser(self, organiser):
        """Sets the organiser of this EventEventdetails.


        :param organiser: The organiser of this EventEventdetails.  # noqa: E501
        :type: EventEventdetailsOrganiser
        """

        self._organiser = organiser

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventEventdetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventEventdetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
